project_name: customError

release:
  github:
    owner: jeanfrancoisgratton
    name: customError

builds: [] # No binaries to build

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'

gomod:
  proxy: true
  download: true

snapshot:
  name_template: "dev"

archives: [] # No archives needed

nfpms: [] # No OS packages (rpm/deb/apk)

